version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    command: npm run dev -- --host
    
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    command: npx nodemon server.js
